Repository Code-Drop-DevAcademy/2024-Team-12, pull requests merged in 2024-06, with the labels that each got.

#3 [Setting] #2 - 깃허브 레포지토리 초기 세팅
  .github/ISSUE_TEMPLATE/basic-issue-template.md
  .github/pull_request_template.md
  .gitignore
Labels: 💤 나기

#6 [Setting] #5 - 프로젝트 추가 및 초기 세팅
  Team12Snail/Team12Snail.xcodeproj/project.pbxproj
  Team12Snail/Team12Snail.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Team12Snail/Team12Snail.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Team12Snail/Team12Snail/Preview Content/Preview Assets.xcassets/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Contents.json
  Team12Snail/Team12Snail/Resource/Constant/StringLiterals.swift
  Team12Snail/Team12Snail/Resource/Extension/View+.swift
  Team12Snail/Team12Snail/Source/App/Team12SnailApp.swift
  Team12Snail/Team12Snail/Source/Model/Item.swift
  Team12Snail/Team12Snail/Source/View/ContentView.swift
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
  Team12Snail/Team12Snail/Source/View/Store/StoreView.swift
  Team12Snail/Team12Snail/Supporting File/Launch Screen.storyboard
Labels: 💤 나기

#9 [Design] #7 Planet View 레이아웃 구현 완료
  Team12Snail/Team12Snail.xcodeproj/project.pbxproj
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar@3x.png
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
  Team12Snail/Team12Snail/Source/View/Planet/StarSelectingView.swift
Labels: 💤 나기

#12 [Feat] #10 - 모델 및 SwiftData 초기 세팅
  Team12Snail/Team12Snail/Source/Model/Item.swift
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
Labels: 🌼 나무디

#14 [Feat]/#11 - 타이머 기능
  Team12Snail/Team12Snail.xcodeproj/project.pbxproj
  Team12Snail/Team12Snail.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Team12Snail/Team12Snail.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Team12Snail/Team12Snail/Preview Content/Preview Assets.xcassets/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/Dummy/ImageDummyPlanet.imageset/ImageDummyPlanet@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/GreenStar.imageset/GreenStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/OrangeStar.imageset/OrangeStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/PinkStar.imageset/PinkStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar@2x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/YellowStar.imageset/YellowStar@3x.png
  Team12Snail/Team12Snail/Resource/Assets.xcassets/star.imageset/Contents.json
  Team12Snail/Team12Snail/Resource/Assets.xcassets/star.imageset/star.png
  Team12Snail/Team12Snail/Resource/Constant/StringLiterals.swift
  Team12Snail/Team12Snail/Resource/Extension/View+.swift
  Team12Snail/Team12Snail/Source/App/Team12SnailApp.swift
  Team12Snail/Team12Snail/Source/Model/Item.swift
  Team12Snail/Team12Snail/Source/View/ContentView.swift
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
  Team12Snail/Team12Snail/Source/View/Planet/StarSelectingView.swift
  Team12Snail/Team12Snail/Source/View/Planet/TimerView.swift
  Team12Snail/Team12Snail/Source/View/Store/StoreView.swift
  Team12Snail/Team12Snail/Supporting File/Launch Screen.storyboard
Labels: 🪄 해라

#18 Design/#17 온보딩 뷰
  Team12Snail/Team12Snail.xcodeproj/project.pbxproj
  Team12Snail/Team12Snail/Source/View/ContentView.swift
  Team12Snail/Team12Snail/Source/View/Planet/OnboardingView.swift
Labels: 🪄 해라

#15 [Design] #13 - StoreView 레이아웃 구현 완료
  Team12Snail/Team12Snail/Source/Model/Item.swift
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
  Team12Snail/Team12Snail/Source/View/Store/StoreView.swift
Labels: 🌼 나무디

#19 [Design]/#17 - 온보딩 기능 데이터 연결
  Team12Snail/Team12Snail/Source/Model/Item.swift
  Team12Snail/Team12Snail/Source/View/ContentView.swift
  Team12Snail/Team12Snail/Source/View/Planet/OnboardingView.swift
  Team12Snail/Team12Snail/Source/View/Planet/PlanetView.swift
Labels: 🪄 해라
